@BodyUrl = http://192.168.20.90:9200
@Index = elrys_film

###
POST {{BodyUrl}}/{{Index}}/_search
Content-Type: application/json

{
    "aggs":{
        "find_data_null":{
            "missing":{
                "field": "genre"
            }
        }
    }
}