GET http://192.168.20.90:9200/rys_acc/_doc/_search


###
POST http://192.168.20.90:9200/_aliases
Content-Type: application/json

{
    "actions" : [
        {
            "add" : {
                "aliases" : "rysacc",
                "index" : "rys_acc"
            }
        }
    ]
}

###
GET http://192.168.20.90:9200/