### TO check the mapping your set earlier
GET http://192.168.20.90:9200/rys_accounts/_mapping

### Last line (id) is primary key in Index
PUT http://192.168.20.90:9200/rys_accounts/_create/5
Content-Type: application/json

  {
    "id": 21265,
    "email": "Nureni@gmail.com",
    "password": "Nureni",
    "register": "2023-10-27T09:11:36.000+00:00",
    "totalLogin": 34,
    "dataModels": [
      {
        "personalId": 21265,
        "name": "Nureni",
        "age": 67,
        "phone": 1821278,
        "country": "korea",
        "city": "busan"
      }
    ],
    "log": [
      {
        "logs_id": 75909,
        "login": "2023-10-27 09:25:49"
      },
      {
        "logs_id": 75910,
        "login": "2023-10-27 09:25:49"
      },
      {
        "logs_id": 75911,
        "login": "2023-10-27 09:25:49"
      },
      {
        "logs_id": 75912,
        "login": "2023-10-27 09:25:49"
      }
    ]
  }
