### Update Index Mapping

PUT http://192.168.20.90:9200/rys_accounts/_mapping
Content-Type: application/json

{
    "numeric_detection" :true,
    "date_detection" : true,
    "dynamic_date_formats" : [
        "yyyy-MM-dd HH:mm:ss",
        "yyyy-MM-dd",
        "yyyy-MM-dd HH:mm:ss",
        "yyyy-MM-dd"
    ]
}


### ceck Mapping Index
GET http://192.168.20.90:9200/rys_accounts/_mapping