### get Index By primary key (id in last line is primary key in rys_accounts index)
GET http://192.168.20.90:9200/rys_accounts/_doc/id

### Get Index without MetaData
GET http://192.168.20.90:9200/rys_accounts/_source/1

### Check Exist
### Just Check index  there or not
HEAD  http://192.168.20.90:9200/rys_accounts/_doc/id
 
