# Index in ElasticSearch same with Table in relational database, like mysql

### create index accouts
PUT http://localhost:9200/account 

### Create Index Logs
PUT http://localhost:9200/logs

### Create Index PersonalData
PUT http://localhost:9200/personal_data

### Create Index Dumps
PUT http://localhost:9200/dumps

# ======================================================

### Get All Index in ElasticSearch
GET http://localhost:9200/_cat/indices?v

# ======================================================

### Delete Index Dumps
DELETE  http://localhost:9200/account

# ======================================================

