### Get multiple Index

### if you declare what index you want to get, you just need _id in ids
POST http://192.168.20.90:9200/rys_accounts/_mget
Content-Type: application/json

{
    "ids" : ["1","2","3"]
}

### If you dont declare index what you want to get, you need insert name index, and _id in doc

POST http://192.168.20.90:9200/_mget
Content-Type: application/json

{
    "docs" : [
        {
            "_id" : "1",
            "_index" : "rys_accounts"
        },
                {
            "_id" : "2",
            "_index" : "logs"
        }
    ]
}

###

POST http://192.168.20.90:9200/_mget
Content-Type: application/json

{
    "docs" : [
        {
            "_id" : "1",
            "_index" : "rys_accounts"
        }
    ]
}


###
